### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ScheduledProgram** [Roblox-Thot/DecalUploaderV2#10]
After attempting to run the program I receive this error

![image_2024-10-27_215520793](https://github.com/user-attachments/assets/f3bc48ac-7a60-4aae-8703-e4ee24702074)

**Comment by Roblox-Thot** [comment]
Make sure you are using the most recent version (just redownload the files)
because I don't use that api to get user info anymore since roblox closed it like a few months ago.

**Comment by ScheduledProgram** [comment]
yooo thank you!

![image](https://github.com/user-attachments/assets/8f4bb16a-0fac-4391-b449-3fd8736a19af)
