### ISSUE TITLE
[Feature] Tshirt option

### ISSUE THREAD

**Issue by ssynical** [Roblox-Thot/DecalUploaderV2#2]
i think having a tshirt option (upload tshirts instead of decals) would be pretty cool and appeal to a larger audience

**Comment by MilkKoun** [comment]
it cant be cuz api dont followed to upload t shirts.

**Comment by Roblox-Thot** [comment]
I'll look into it but no promises

**Comment by Roblox-Thot** [comment]
Ya sadly the Roblox's API cloud doesn't support anything other than Decal, Model, and Audio

Source: https://create.roblox.com/docs/en-us/cloud/open-cloud/usage-assets#supported-asset-types-and-limits
