### ISSUE TITLE
NOT A QUESTION

### ISSUE THREAD

**Issue by ssynical** [Roblox-Thot/DecalUploaderV2#4]
**Simply a question I'd like to ask**

I would like to ask what exactly you can do with an apiKey, just curious.

**Comment by Roblox-Thot** [comment]
There isn't a whole lot made public on the api _yet_ but this is kinda a list of whats possible right now using the open cloud api

![image](https://github.com/Roblox-Thot/DecalUploaderV2/assets/67937010/59b0879a-4e50-4eda-a95d-82b265bf405a)
